version: '3'
services:
  #服务注册发现
  peer1:
    hostname: peer1
    container_name: peer1
    build: eureka-server/
    image: springcloud/eureka-server:latest
    networks:
      - springcloud-network
    ports:
      - 8761:8761
    environment:
      - spring.profiles.active=peer1
  peer2:
    hostname: peer2
    container_name: peer2
    build: eureka-server/
    image: springcloud/eureka-server:latest
    networks:
      - springcloud-network
    ports:
      - 8762:8762
    environment:
      - spring.profiles.active=peer2
  peer3:
    hostname: peer3
    container_name: peer3
    build: eureka-server/
    image: springcloud/eureka-server:latest
    networks:
      - springcloud-network
    ports:
      - 8763:8763
    environment:
      - spring.profiles.active=peer3

  #配置中心
  config-server:
    hostname: config-server
    container_name: config-server
    build: config-server/
    image: springcloud/config-server:latest
    networks:
      - springcloud-network
    ports:
      - 8800:8800
    depends_on:
      - peer1
      - peer2
      - peer3
  #控制平台
  console:
    hostname: console
    container_name: console
    build: console/
    image: springcloud/console:latest
    networks:
      - springcloud-network
    ports:
      - 2222:2222
    depends_on:
      - config-server

  dashboard:
    hostname: dashboard
    container_name: dashboard
    build: dashboard/
    image: springcloud/dashboard:latest
    networks:
      - springcloud-network
    ports:
      - 8900:8900
    depends_on:
      - peer1
      - peer2
      - peer3
      - config-server

#  trace:
#    hostname: trace
#    container_name: trace
#    build: trace/
#    image: springcloud/trace:latest
#    networks:
#      - springcloud-network
#    ports:
#      - 9411:9411
#    depends_on:
#      - peer1
#      - peer2
#      - peer3
#      - config-server

networks:
  springcloud-network:
    external: true
  apollo-network:
    external: true